version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - '8000:3333'
    volumes:
      - ./store:/store
    depends_on:
      - queue

  queue:
    image: rabbitmq:management
    hostname: rabbit
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - '15672:15672'

volumes:
  rabbitmq: